import { z } from "zod";
import { AGENT_CLIENTS } from "../services/agent-manifest.js";
import { DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE } from "../constants.js";

export const ResponseFormatSchema = z.enum(["markdown", "json"]).default("markdown");
export const AgentClientSchema = z.enum(AGENT_CLIENTS).default("generic");
export const PrivacyModeValueSchema = z.enum(["summary", "structured", "raw"]);
export const PrivacyModeSchema = PrivacyModeValueSchema.optional()
  .describe("Optional per-call payload privacy override. Defaults to GOOGLE_ADS_PRIVACY_MODE or structured.");

/** Google Ads customer id (10 digits, dashes allowed and stripped). */
export const CustomerIdSchema = z.string().min(7).max(20)
  .describe("Google Ads customer id (10 digits). Dashes optional, e.g. '1234567890' or '123-456-7890'.");

export const ResponseOnlyInputSchema = z.object({
  response_format: ResponseFormatSchema
}).strict();

export const AgentManifestInputSchema = z.object({
  client: AgentClientSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ConnectionStatusInputSchema = z.object({
  client: AgentClientSchema.optional(),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlInputSchema = z.object({
  state: z.string().max(500).optional().describe("Optional OAuth state value generated by the caller."),
  scopes: z.array(z.string()).optional().describe("Optional scope override. Defaults to the Google Ads scope."),
  response_format: ResponseFormatSchema
}).strict();

export const ExchangeCodeInputSchema = z.object({
  code: z.string().min(1).describe("OAuth authorization code, or a full redirect URL containing ?code=..."),
  response_format: ResponseFormatSchema
}).strict();

export const ListAccountsInputSchema = z.object({
  response_format: ResponseFormatSchema
}).strict();

export const ListCampaignsInputSchema = z.object({
  customer_id: CustomerIdSchema,
  status: z.enum(["ENABLED", "PAUSED", "REMOVED", "ALL"]).default("ENABLED")
    .describe("Filter by campaign status. Use ALL to include every status."),
  page_size: z.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const GetCampaignInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_id: z.string().min(1).describe("Google Ads campaign id (numeric)."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ListAdGroupsInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_id: z.string().optional().describe("Optional campaign id filter."),
  status: z.enum(["ENABLED", "PAUSED", "REMOVED", "ALL"]).default("ENABLED"),
  page_size: z.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ListKeywordsInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_id: z.string().optional().describe("Optional campaign id filter."),
  ad_group_id: z.string().optional().describe("Optional ad group id filter."),
  status: z.enum(["ENABLED", "PAUSED", "REMOVED", "ALL"]).default("ENABLED"),
  page_size: z.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const DateRangeSchema = z.enum([
  "TODAY", "YESTERDAY", "LAST_7_DAYS", "LAST_14_DAYS", "LAST_30_DAYS", "THIS_MONTH", "LAST_MONTH"
]).describe("Predefined date range supported by Google Ads GAQL.");

export const PerformanceInputSchema = z.object({
  customer_id: CustomerIdSchema,
  date_range: DateRangeSchema.default("LAST_30_DAYS"),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const CampaignPerformanceInputSchema = PerformanceInputSchema.extend({
  campaign_id: z.string().optional().describe("Optional single-campaign filter.")
}).strict();

export const KeywordPerformanceInputSchema = PerformanceInputSchema.extend({
  campaign_id: z.string().optional(),
  ad_group_id: z.string().optional(),
  min_clicks: z.number().int().min(0).default(0)
    .describe("Filter out keywords with fewer than this many clicks (defensive baseline filter).")
}).strict();

export const DailyReportInputSchema = z.object({
  customer_id: CustomerIdSchema,
  cpc_alert_threshold: z.number().min(0).optional()
    .describe("Optional CPC threshold in account currency. If yesterday's CPC exceeds this, the report adds an ALERT block."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const FindWasteInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_id: z.string().optional(),
  date_range: DateRangeSchema.default("LAST_30_DAYS"),
  min_clicks: z.number().int().min(1).default(5)
    .describe("Minimum clicks to evaluate (skip low-data keywords)."),
  min_cost_micros: z.number().int().min(0).default(200_000)
    .describe("Cost floor in micros. Default 200_000 = $0.20 — adjust to taste."),
  zero_conversions_only: z.boolean().default(true)
    .describe("If true (default), only include keywords with 0 conversions."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const QuickWinsInputSchema = z.object({
  customer_id: CustomerIdSchema,
  lookback_days: z.number().int().min(1).max(90).default(30)
    .describe("Look-back window in days (1-90). Converted into the GAQL DATE_RANGE/BETWEEN clause."),
  min_ctr: z.number().min(0).max(100).default(5)
    .describe("Minimum CTR in percent (e.g., 5 = 5%). Default 5%."),
  max_avg_cpc_micros: z.number().int().min(0).default(100_000)
    .describe("Maximum average CPC in micros. Default 100_000 ($0.10)."),
  min_conversions: z.number().min(0).default(0.5)
    .describe("Minimum conversions in the window. Default 0.5 (at least half a conversion)."),
  limit: z.number().int().min(1).max(200).default(50)
    .describe("Maximum candidates to return."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

// Mutation input schemas
export const MutationGateSchema = z.object({
  explicit_user_intent: z.boolean().describe("Must be true. Set this AFTER the user has explicitly confirmed they want to apply this mutation.")
});

export const PauseKeywordInputSchema = z.object({
  customer_id: CustomerIdSchema,
  ad_group_id: z.string().min(1).describe("Ad group that owns the keyword criterion."),
  criterion_id: z.string().min(1).describe("Keyword criterion id (the keyword's id, NOT the keyword text)."),
  explicit_user_intent: z.boolean(),
  response_format: ResponseFormatSchema
}).strict();

export const ResumeKeywordInputSchema = PauseKeywordInputSchema;

export const SetKeywordBidInputSchema = z.object({
  customer_id: CustomerIdSchema,
  ad_group_id: z.string().min(1),
  criterion_id: z.string().min(1),
  cpc_bid_micros: z.number().int().min(10_000).max(1_000_000_000)
    .describe("Max CPC bid in micros. 10_000 = $0.01 minimum, 1_000_000_000 = $1000 maximum."),
  explicit_user_intent: z.boolean(),
  response_format: ResponseFormatSchema
}).strict();

export const SetCampaignBudgetInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_budget_id: z.string().min(1)
    .describe("Campaign budget id (NOT the campaign id). Discover via google_ads_get_campaign — returns campaign_budget.id."),
  amount_micros: z.number().int().min(10_000).max(10_000_000_000_000)
    .describe("Daily budget amount in micros. 10_000 = $0.01 minimum."),
  explicit_user_intent: z.boolean(),
  response_format: ResponseFormatSchema
}).strict();

export const CampaignStatusToggleInputSchema = z.object({
  customer_id: CustomerIdSchema,
  campaign_id: z.string().min(1),
  explicit_user_intent: z.boolean(),
  response_format: ResponseFormatSchema
}).strict();

// Output schemas — fully optional so both happy and error paths validate.
export const StandardOutputSchema = z.looseObject({
  ok: z.boolean().optional(),
  privacy_mode: PrivacyModeValueSchema.optional(),
  error: z.string().optional()
});

export const CollectionOutputSchema = z.looseObject({
  ok: z.boolean().optional(),
  privacy_mode: PrivacyModeValueSchema.optional(),
  count: z.number().int().nonnegative().optional(),
  records: z.array(z.unknown()).optional(),
  next_page_token: z.string().optional(),
  has_more: z.boolean().optional(),
  error: z.string().optional()
});

// Loose + all-optional so both success and error responses validate (makeError
// returns `{ error }` only; happy path returns ok + applied + resource).
export const MutationOutputSchema = z.looseObject({
  ok: z.boolean().optional(),
  resource: z.string().optional(),
  applied: z.boolean().optional(),
  reverted: z.boolean().optional(),
  note: z.string().optional(),
  error: z.string().optional()
});

export const CacheStatusOutputSchema = z.looseObject({
  cache_enabled: z.boolean(),
  cache_path: z.string(),
  entries_count: z.number().int().nonnegative(),
  oldest_age_ms: z.number().nonnegative().optional(),
  newest_age_ms: z.number().nonnegative().optional(),
  default_ttl_seconds: z.number().int().nonnegative().optional()
});

export const CacheClearOutputSchema = z.looseObject({
  cache_enabled: z.boolean(),
  cache_path: z.string(),
  cleared_entries: z.number().int().nonnegative()
});

export const AuthUrlOutputSchema = z.object({
  auth_url: z.string(),
  redirect_uri: z.string(),
  scopes: z.array(z.string()),
  next_step: z.string()
}).strict();

export const ExchangeCodeOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  scope: z.string().optional(),
  expires_at: z.number().optional(),
  has_refresh_token: z.boolean(),
  note: z.string()
}).strict();

export const RevokeAccessOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  local_tokens_cleared: z.boolean(),
  note: z.string()
}).strict();

export const CapabilitiesOutputSchema = z.looseObject({
  project: z.string(),
  mcp_name: z.string(),
  unofficial: z.boolean()
});

export const AgentManifestOutputSchema = z.looseObject({
  project: z.string(),
  mcp_name: z.string(),
  client: AgentClientSchema,
  unofficial: z.boolean()
});

export const ConnectionStatusOutputSchema = z.looseObject({
  ok: z.boolean(),
  ready_for_google_ads_api: z.boolean()
});

// Use loose() instead of passthrough() — MCP SDK builds JSON Schema from Zod, and
// passthrough() can still emit `additionalProperties: false` for some shapes; loose()
// emits `additionalProperties: true` so dynamic fields (audit, capabilities) validate.
export const PrivacyAuditOutputSchema = z.looseObject({
  project: z.string(),
  unofficial: z.boolean(),
  mutations_allowed: z.boolean(),
  privacy_mode_default: PrivacyModeValueSchema
});

export const DataInventoryOutputSchema = z.looseObject({
  kind: z.literal("data_inventory"),
  source: z.string(),
  mcp_name: z.string()
});

export type ListCampaignsInput = z.infer<typeof ListCampaignsInputSchema>;
export type ListAdGroupsInput = z.infer<typeof ListAdGroupsInputSchema>;
export type ListKeywordsInput = z.infer<typeof ListKeywordsInputSchema>;
export type PerformanceInput = z.infer<typeof PerformanceInputSchema>;
export type CampaignPerformanceInput = z.infer<typeof CampaignPerformanceInputSchema>;
export type KeywordPerformanceInput = z.infer<typeof KeywordPerformanceInputSchema>;
export type DailyReportInput = z.infer<typeof DailyReportInputSchema>;
export type FindWasteInput = z.infer<typeof FindWasteInputSchema>;
export type QuickWinsInput = z.infer<typeof QuickWinsInputSchema>;
